// angular/src/app/components/auth/login.component.ts
import { Component, signal, output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  imports: [FormsModule],
  template: `
    <div class="auth-card">
      <h2 class="auth-title">Login</h2>

      @if (error()) {
        <p class="error-msg">{{ error() }}</p>
      }

      <form (ngSubmit)="handleSubmit()">
        <div class="auth-field">
          <label>Email:</label>
          <input
            [(ngModel)]="email"
            name="email"
            type="email"
            placeholder="Enter your email"
          />
        </div>

        <div class="auth-field">
          <label>Password:</label>
          <input
            [(ngModel)]="password"
            name="password"
            type="password"
            placeholder="Enter your password"
          />
        </div>

        <button type="submit" class="auth-btn">Login</button>
      </form>

      <div class="auth-switch">
        New user? <span (click)="switchToRegister.emit()">Create an account</span>
      </div>
    </div>
  `,
  styles: ``
})
export class LoginComponent {
  email = '';
  password = '';
  error = signal('');
  
  switchToRegister = output<void>();

  constructor(private authService: AuthService) {}

  async handleSubmit(): Promise<void> {
    try {
      await this.authService.login(this.email, this.password);
    } catch (err: any) {
      this.error.set(err.message || 'Login failed');
    }
  }
}

// react/src/Login.tsx
import React, { useState, useContext } from "react";
import { AuthContext } from "./AuthContext";
import "./style.css";

export function Login({ switchToRegister }: { switchToRegister: () => void }) {
  const auth = useContext(AuthContext);
  if (!auth) throw new Error("AuthContext not found");

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await auth.login(email, password);
    } catch (err: any) {
      setError(err.message);
    }
  };

  return (
    <div className="auth-card">
      <h2 className="auth-title">Login</h2>

      {error && <p className="error-msg">{error}</p>}

      <form onSubmit={handleSubmit}>
        <div className="auth-field">
          <label>Email:</label>
          <input
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            type="email"
            placeholder="Enter your email"
          />
        </div>

        <div className="auth-field">
          <label>Password:</label>
          <input
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            placeholder="Enter your password"
          />
        </div>

        <button type="submit" className="auth-btn">
          Login
        </button>
      </form>

      <div className="auth-switch">
        New user? <span onClick={switchToRegister}>Create an account</span>
      </div>
    </div>
  );
}
