// nextjs/app/page.tsx
"use client";

import { useContext } from "react";
import { AuthContext } from "./context/AuthContext";
import { authClient } from "@/lib/auth-client";
import { Auth } from "./components/Auth/Auth";
import ItemsComponent from "./components/Items/Items";

export default function Home() {
  const { data: session, isPending } = authClient.useSession();
  const auth = useContext(AuthContext);

  if (isPending) {
    return <div className="loading">Loading...</div>;
  }

  if (!session) {
    return <Auth />;
  }

  return (
    <div className="app-wrapper">
      <div className="app-header">
        <h1>MERN Starter CRUD (Authenticated)</h1>

        <button className="logout-btn" onClick={() => auth?.logout()}>
          Logout
        </button>
      </div>

      <ItemsComponent />
    </div>
  );
}

// vuejs/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { authClient } from '@/lib/auth-client'
import { useAuthStore } from '@/stores/auth'
import Auth from '@/components/Auth/Auth.vue'
import ItemsList from '@/components/Items/ItemsList.vue'

const auth = useAuthStore()
const { data: session, isPending } = authClient.useSession()
const isLoggedIn = ref(false)

// Watch session changes
session.value ? (isLoggedIn.value = true) : (isLoggedIn.value = false)
</script>

<template>
  <div v-if="isPending" class="loading">Loading...</div>

  <div v-else-if="!session">
    <Auth />
  </div>

  <div v-else class="app-wrapper">
    <div class="app-header">
      <h1>MERN Starter CRUD (Authenticated)</h1>

      <button class="logout-btn" @click="auth.logout()">Logout</button>
    </div>

    <ItemsList />
  </div>
</template>
