// react/src/Auth.tsx
import React, { useState } from "react";
import { Login } from "./Login";
import { Register } from "./Register";

export function Auth() {
  const [mode, setMode] = useState<"login" | "register">("login");

  return (
    <>
      {mode === "login" && (
        <Login switchToRegister={() => setMode("register")} />
      )}

      {mode === "register" && (
        <Register switchToLogin={() => setMode("login")} />
      )}
    </>
  );
}

// angular/src/app/components/auth/auth.component.ts
import { Component, signal } from '@angular/core';
import { LoginComponent } from './login.component';
import { RegisterComponent } from './register.component';

@Component({
  selector: 'app-auth',
  imports: [LoginComponent, RegisterComponent],
  template: `
    @if (mode() === 'login') {
      <app-login (switchToRegister)="mode.set('register')" />
    }
    
    @if (mode() === 'register') {
      <app-register (switchToLogin)="mode.set('login')" />
    }
  `,
  styles: ``
})
export class AuthComponent {
  mode = signal<'login' | 'register'>('login');
}
