// nextjs/app/components/Auth/Register.tsx
"use client";

import React, { useState, useContext } from "react";
import { AuthContext } from "../../context/AuthContext";

export function Register({ switchToLogin }: { switchToLogin: () => void }) {
  const auth = useContext(AuthContext);
  if (!auth) throw new Error("AuthContext not found");

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | string[]>("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    
    try {
      await auth.register(email, password);
      switchToLogin();
    } catch (err: any) {
      // Backend may return: { errors: [...] } or { message: "..." }
      if (err?.response?.data?.errors) {
        // Extract express-validator error messages
        setError(err.response.data.errors.map((e: any) => e.msg));
      } else {
        setError(err?.message || "Registration failed");
      }
    }
  };

  return (
    <div className="auth-card">
      <h2 className="auth-title">Register</h2>

      {/* Show single or multiple error messages */}
      {error &&
        (Array.isArray(error) ? (
          <ul className="error-msg">
            {error.map((msg, i) => (
              <li key={i}>{msg}</li>
            ))}
          </ul>
        ) : (
          <p className="error-msg">{error}</p>
        ))}

      <form onSubmit={handleSubmit}>
        <div className="auth-field">
          <label>Email:</label>
          <input
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            type="email"
            placeholder="Enter your email"
          />
        </div>

        <div className="auth-field">
          <label>Password:</label>
          <input
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            placeholder="Create a strong password"
          />
        </div>

        <button type="submit" className="auth-btn">
          Register
        </button>
      </form>

      <div className="auth-switch">
        Already have an account? <span onClick={switchToLogin}>Login here</span>
      </div>
    </div>
  );
}

// angular/src/app/components/auth/register.component.ts
import { Component, signal, output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  imports: [FormsModule],
  template: `
    <div class="auth-card">
      <h2 class="auth-title">Register</h2>

      @if (error()) {
        @if (errorArray()) {
          <ul class="error-msg">
            @for (msg of errorArray(); track msg) {
              <li>{{ msg }}</li>
            }
          </ul>
        } @else {
          <p class="error-msg">{{ error() }}</p>
        }
      }

      <form (ngSubmit)="handleSubmit()">
        <div class="auth-field">
          <label>Email:</label>
          <input
            [(ngModel)]="email"
            name="email"
            type="email"
            placeholder="Enter your email"
          />
        </div>

        <div class="auth-field">
          <label>Password:</label>
          <input
            [(ngModel)]="password"
            name="password"
            type="password"
            placeholder="Create a strong password"
          />
        </div>

        <button type="submit" class="auth-btn">Register</button>
      </form>

      <div class="auth-switch">
        Already have an account? <span (click)="switchToLogin.emit()">Login here</span>
      </div>
    </div>
  `,
  styles: ``
})
export class RegisterComponent {
  email = '';
  password = '';
  error = signal<string>('');
  errorArray = signal<string[] | null>(null);

  switchToLogin = output<void>();

  constructor(private authService: AuthService) { }

  async handleSubmit(): Promise<void> {
    this.error.set('');
    this.errorArray.set(null);

    try {
      await this.authService.register(this.email, this.password);
      this.switchToLogin.emit();
    } catch (err: any) {
      // Backend may return: { errors: [...] } or { message: "..." }
      if (err?.response?.data?.errors) {
        this.errorArray.set(err.response.data.errors.map((e: any) => e.msg));
      } else {
        this.error.set(err?.response?.data?.message || err.message || 'Registration failed');
      }
    }
  }
}
