// react/src/components/Items/Items.tsx
import { useEffect, useState } from "react";
import api from "../../api/api";

interface Item {
  _id: string;
  name: string;
}

export default function ItemsComponent({
  accessToken,
}: {
  accessToken: string;
}) {
  const [items, setItems] = useState<Item[]>([]);
  const [newItem, setNewItem] = useState("");

  async function fetchItems() {
    const data = await api.authGet("/api/items", accessToken);
    setItems(data);
  }

  async function addItem() {
    if (!newItem.trim()) return;

    const res = await fetch("http://localhost:5000/api/items", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ name: newItem }),
    });

    const created = await res.json();
    setItems([...items, created]);
    setNewItem("");
  }

  async function deleteItem(id: string) {
    await api.authDelete(`/api/items/${id}`, accessToken);
    setItems(items.filter((i) => i._id !== id));
  }

  useEffect(() => {
    fetchItems();
  }, []);

  return (
    <div>
      <div className="add-item-box">
        <input
          value={newItem}
          onChange={(e) => setNewItem(e.target.value)}
          placeholder="New item name"
        />
        <button className="add-item-btn" onClick={addItem}>
          Add
        </button>
      </div>

      <ul className="item-list">
        {items.map((item) => (
          <li key={item._id} className="item">
            {item.name}
            <button className="delete-btn" onClick={() => deleteItem(item._id)}>
              Delete
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}

// angular/src/app/components/items/items.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

const API_BASE = 'http://localhost:5000';

interface Item {
  _id: string;
  name: string;
}

@Component({
  selector: 'app-items',
  imports: [FormsModule],
  template: `
    <div>
      <div class="add-item-box">
        <input
          [(ngModel)]="newItem"
          name="newItem"
          placeholder="New item name"
        />
        <button class="add-item-btn" (click)="addItem()">Add</button>
      </div>

      <ul class="item-list">
        @for (item of items(); track item._id) {
          <li class="item">
            {{ item.name }}
            <button class="delete-btn" (click)="deleteItem(item._id)">Delete</button>
          </li>
        }
      </ul>
    </div>
  `,
  styles: ``
})
export class ItemsComponent implements OnInit {
  items = signal<Item[]>([]);
  newItem = '';

  async fetchItems(): Promise<void> {
    const res = await fetch(`${API_BASE}/api/items`, { credentials: 'include' });
    const data = await res.json();
    this.items.set(data);
  }

  ngOnInit(): void {
    this.fetchItems();
  }

  async addItem(): Promise<void> {
    if (!this.newItem.trim()) return;

    const res = await fetch(`${API_BASE}/api/items`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ name: this.newItem }),
    });

    const created = await res.json();
    this.items.set([...this.items(), created]);
    this.newItem = '';
  }

  async deleteItem(id: string): Promise<void> {
    await fetch(`${API_BASE}/api/items/${id}`, {
      method: 'DELETE',
      credentials: 'include',
    });
    this.items.set(this.items().filter(i => i._id !== id));
  }
}
