// react/src/Items.tsx
import { useEffect, useState } from "react";
import "./style.css";

interface ItemsProps {
  accessToken: string;
}

interface Item {
  _id?: string;
  name: string;
}

function ItemsComponent({ accessToken }: ItemsProps) {
  
  const [items, setItems] = useState<Item[]>([]);
  const [newItem, setNewItem] = useState<string>("");

  useEffect(() => {
    const fetchItems = async () => {
      try {
        const res = await fetch(API_URL.trim());
        const data = await res.json();
        setItems(data);
      } catch (err) {
        console.error("Error fetching items:", err);
      }
    };
    fetchItems();
  }, []);

  const API_URL = `${
    import.meta.env.VITE_API_BASE_URL || "http://localhost:5000"
  }/api/items`;

  const fetchItems = async () => {
    const res = await fetch(API_URL, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    const data = await res.json();
    setItems(data);
  };

  const addItem = async () => {
    if (!newItem.trim()) return;
    await fetch(API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      },
      body: JSON.stringify({ name: newItem }),
    });
    setNewItem("");
    fetchItems();
  };

  const deleteItem = async (id: string) => {
    await fetch(`${API_URL}/${id}`, {
      method: "DELETE",
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    setItems(items.filter((i) => i._id !== id));
  };

  useEffect(() => {
    fetchItems();
  }, [accessToken]);

  return (
    <div className="app-wrapper">
      <div className="add-item-box">
        <input
          type="text"
          value={newItem}
          onChange={(e) => setNewItem(e.target.value)}
          placeholder="New item name"
        />
        <button className="add-item-btn" onClick={addItem}>
          Add
        </button>
      </div>

      <ul className="item-list">
        {items.map((item) => (
          <li key={item._id} className="item">
            {item.name}
            <button
              className="delete-btn"
              onClick={() => item._id && deleteItem(item._id)}
            >
              Delete
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}
export default ItemsComponent;

// angular/src/app/components/items/items.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

const API_BASE = 'http://localhost:5000';

interface Item {
  _id: string;
  name: string;
}

@Component({
  selector: 'app-items',
  imports: [FormsModule],
  template: `
    <div>
      <div class="add-item-box">
        <input
          [(ngModel)]="newItem"
          name="newItem"
          placeholder="New item name"
        />
        <button class="add-item-btn" (click)="addItem()">Add</button>
      </div>

      <ul class="item-list">
        @for (item of items(); track item._id) {
          <li class="item">
            {{ item.name }}
            <button class="delete-btn" (click)="deleteItem(item._id)">Delete</button>
          </li>
        }
      </ul>
    </div>
  `,
  styles: ``
})
export class ItemsComponent implements OnInit {
  items = signal<Item[]>([]);
  newItem = '';

  async fetchItems(): Promise<void> {
    const res = await fetch(`${API_BASE}/api/items`, { credentials: 'include' });
    const data = await res.json();
    this.items.set(data);
  }

  ngOnInit(): void {
    this.fetchItems();
  }

  async addItem(): Promise<void> {
    if (!this.newItem.trim()) return;

    const res = await fetch(`${API_BASE}/api/items`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ name: this.newItem }),
    });

    const created = await res.json();
    this.items.set([...this.items(), created]);
    this.newItem = '';
  }

  async deleteItem(id: string): Promise<void> {
    await fetch(`${API_BASE}/api/items/${id}`, {
      method: 'DELETE',
      credentials: 'include',
    });
    this.items.set(this.items().filter(i => i._id !== id));
  }
}
